name: "白泽"
mode: "dev"
port: 8080
version: "v1.0.2"
start_time: "2021-05-07"
machine_id: 1
profile: "D:/baize/uploadPath"
log:
  level: "info"
  filename: "D:/baizelog/baizelog.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: 127.0.0.1
  port: 3306
  user: "root"
  password: "123456"
  dbname: "baize"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 1
  pool_size: 100
token:
  expireTime: 30
  secret: abcdefghijklmnopqrstuvwxyz
  issuer: baize